// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Zx9AbRon75S69DT6QjtFdyaPjq7eFPA',
    appId: '1:221599281981:web:6eaa25a0597a76d8d70b54',
    messagingSenderId: '221599281981',
    projectId: 'perfume-app-c3a0c',
    authDomain: 'perfume-app-c3a0c.firebaseapp.com',
    storageBucket: 'perfume-app-c3a0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXF0Acb3MNnUa9xYJmnuayagbb7qwTeUY',
    appId: '1:221599281981:android:f9eb5fb298f1455ad70b54',
    messagingSenderId: '221599281981',
    projectId: 'perfume-app-c3a0c',
    storageBucket: 'perfume-app-c3a0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhSGSM8NgpGh9fUrdDaLn1HQrYHYVpLLs',
    appId: '1:221599281981:ios:ef75a982b3c42ba6d70b54',
    messagingSenderId: '221599281981',
    projectId: 'perfume-app-c3a0c',
    storageBucket: 'perfume-app-c3a0c.firebasestorage.app',
    iosBundleId: 'com.example.perfumeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhSGSM8NgpGh9fUrdDaLn1HQrYHYVpLLs',
    appId: '1:221599281981:ios:ef75a982b3c42ba6d70b54',
    messagingSenderId: '221599281981',
    projectId: 'perfume-app-c3a0c',
    storageBucket: 'perfume-app-c3a0c.firebasestorage.app',
    iosBundleId: 'com.example.perfumeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Zx9AbRon75S69DT6QjtFdyaPjq7eFPA',
    appId: '1:221599281981:web:2b19ed15be8ad878d70b54',
    messagingSenderId: '221599281981',
    projectId: 'perfume-app-c3a0c',
    authDomain: 'perfume-app-c3a0c.firebaseapp.com',
    storageBucket: 'perfume-app-c3a0c.firebasestorage.app',
  );
}
